### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by BullyWiiPlaza** [archshift/xorer#7]
When I follow your guide on building xorer the final make command is not working:
make: **\* No targets specified and no makefile found. Stop.
https://github.com/archshift/xorer#building-xorer

Did you screw up on the building instructions? Obviously I have cmake installed and the previous steps all worked fine.

Thank you!

**Comment by archshift** [comment]
What platform are you on?

**Comment by BullyWiiPlaza** [comment]
Windows 8.1

**Comment by archshift** [comment]
Under Windows, CMake uses Visual Studio as the default generator, so either you'll have to compile it by opening the generated solution file in Visual Studio, or you'll have to specify `-G "Unix Makefiles"` with CMake.

**Comment by BullyWiiPlaza** [comment]
Yeah, using `Microsoft Visual Studio Ultimate 2013` and `Build Solution` it now generated `xorer.exe` in `xorer-master\build\Debug`. Thank you.
