### ISSUE TITLE
Cannot allocate enough ram on Windows (ftell quirk)

### ISSUE THREAD

**Issue by jroweboy** [archshift/xorer#9]
in the ReadBinaryFile function in file_io.cpp there is a part where you gather the file size by using fseek and ftell. Outside of this method having [security implications](https://www.securecoding.cert.org/confluence/display/seccode/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file) (which probably isn't a real issue in practice) it flat out doesn't work on windows since it gets 0xFFFFFFFFFFFFFFFF as the size of the file and throws a bad alloc.

Below is my VERY BAD version of how I patched it temporarily to get it to work on Windows. I know its horrible which is why I'm not opening a PR for it. Gotta love coding at 4AM

```
int fh, result;
unsigned int nbytes = BUFSIZ;

// Open a file 
if (_sopen_s(&fh, filename.c_str(), _O_RDONLY, _SH_DENYRW, _S_IREAD) == 0)
{
    __int64 out_size = _filelengthi64(fh);
    _close(fh);

    std::vector<u8> file_buf(out_size);
    FILE* bin_file = fopen(filename.c_str(), "rb");
    fread(&file_buf[0], 1, file_buf.size(), bin_file);
    fclose(bin_file);
    return file_buf;
}
```

**Comment by mhvuze** [comment]
Hi,

I've just run into this issue too, so thanks for offering this quick workaround. I applied it to file_io.cpp by replacing the previous code, however now xorer throws a "r6010 abort has been called" when trying to handle the input files. Building works fine, did I miss something?

```
std::vector<u8> ReadBinaryFile(const std::string& filename)
{
    int fh, result;
    unsigned int nbytes = BUFSIZ;

    // Open a file 
    if (_sopen_s(&fh, filename.c_str(), _O_RDONLY, _SH_DENYRW, _S_IREAD) == 0)
    {
        __int64 out_size = _filelengthi64(fh);
        _close(fh);

        std::vector<u8> file_buf(out_size);
        FILE* bin_file = fopen(filename.c_str(), "rb");
        fread(&file_buf[0], 1, file_buf.size(), bin_file);
        fclose(bin_file);
        return file_buf;
    }

};
```

Sorry for the inconvenience I'm quite code-illiterate, haha.

**Comment by jroweboy** [comment]
@mhvuze First off, is your system 32 bit or 64 bit? This code is for 64 bit systems. If you are on 64 bit then let me know and I'll see what I can do later today

**Comment by mhvuze** [comment]
@jroweboy Yes, I'm on Win7 64bit. Thanks for your help!

**Comment by jroweboy** [comment]
@mhvuze it sounds like it compiled and then aborted during runtime which is weird. I guess that means that you managed to get it to compile by `#include` the right headers then? If not here is a gist of the full file I used to compile it. It seems to work for me. If there is something else wrong it may be worth opening another ticket for it. https://gist.github.com/jroweboy/6d08999055a0df421879

**Comment by mhvuze** [comment]
@jroweboy Yes, I did include the right headers and got it to build. I tried using your file and made sure it builds to x64 but I get a bun of linker errors related to the crypto stuff (I think) now ugh. I guess I'll just take the fixed executable if you would be so kind to share it with me. Thanks again for trying to help!

**Comment by jroweboy** [comment]
well here is the compiled version. https://drive.google.com/file/d/0B8hW8rreabPRbkh4bklHdHduWFE/view?usp=sharing I just tried it and it worked for me so I hope it also works for you as well.

**Comment by mhvuze** [comment]
Thank you very much, it works just fine! Not sure where I messed up haha. Cheers :)

**Comment by archshift** [comment]
This definitely shouldn't be an issue anymore. Can you verify?

**Comment by mhvuze** [comment]
Works fine now, thank you!
